import type { MusicEvent } from '~/types'

/**
 * ⚠ SEED DATA — VERIFY BEFORE PUBLISHING ⚠
 *
 * Starter event data so the app is usable during the first week of use.
 * Many entries are real and well-documented; some may need date/detail
 * corrections — treat this as a curation backlog, not a source of truth.
 * Every event should be fact-checked (sources[] URL) before a video goes live.
 *
 * Covers: 2026-04-19 (today) through 2026-04-25 (one week out).
 * Replace with a MongoDB-backed DB via the seed scraper once built.
 */
export const MOCK_EVENTS: MusicEvent[] = [
  // ─────────────────────────────────────────────── 04-19 ──
  {
    _id: 'seed-0419-1',
    date: '04-19',
    year: 1994,
    category: 'hip-hop',
    event_type: 'release',
    headline: 'Nas releases "Illmatic"',
    artist: 'Nas',
    album: 'Illmatic',
    summary: 'Debut album widely considered one of the greatest hip-hop records of all time. Produced by DJ Premier, Large Professor, Pete Rock, Q-Tip, and L.E.S.',
    sources: ['https://en.wikipedia.org/wiki/Illmatic'],
    interestingness_score: 9.8,
    hook_types: ['legacy', 'debut'],
    angles_available: ['the_release', 'production', 'chart_run', 'legacy', 'one_song_deep_dive'],
    angles_used: [],
  },
  {
    _id: 'seed-0419-2',
    date: '04-19',
    year: 1967,
    category: 'rock',
    event_type: 'release',
    headline: 'Pink Floyd release "Arnold Layne" in the US',
    artist: 'Pink Floyd',
    summary: 'Debut single about a cross-dressing clothes thief, banned by several UK radio stations. Syd Barrett\'s quirky songwriting front and centre.',
    sources: ['https://en.wikipedia.org/wiki/Arnold_Layne'],
    interestingness_score: 7.1,
    hook_types: ['controversy', 'debut'],
    angles_available: ['the_release', 'the_controversy', 'syd_barrett', 'the_ban'],
    angles_used: [],
  },
  {
    _id: 'seed-0419-3',
    date: '04-19',
    year: 2001,
    category: 'pop',
    event_type: 'chart',
    headline: '"Lady Marmalade" cover hits #1 UK',
    artist: 'Christina Aguilera, Lil\' Kim, Mýa, Pink',
    album: 'Moulin Rouge! OST',
    summary: 'Cover of the 1974 LaBelle classic for the Moulin Rouge! soundtrack. VMA-winning video, global chart-topper.',
    sources: ['https://en.wikipedia.org/wiki/Lady_Marmalade'],
    interestingness_score: 6.2,
    hook_types: ['cover', 'collab'],
    angles_available: ['the_release', 'the_original', 'the_music_video', 'collab_dynamics'],
    angles_used: [],
  },
  {
    _id: 'seed-0419-4',
    date: '04-19',
    year: 1989,
    category: 'pop',
    event_type: 'controversy',
    headline: 'Madonna\'s "Like a Prayer" Pepsi ad pulled',
    artist: 'Madonna',
    summary: 'Pepsi pulls a $5m Madonna sponsorship after backlash to the "Like a Prayer" music video\'s religious imagery.',
    sources: ['https://en.wikipedia.org/wiki/Like_a_Prayer_(song)'],
    interestingness_score: 8.0,
    hook_types: ['controversy', 'lawsuit'],
    angles_available: ['the_event', 'pepsi_fallout', 'the_video', 'the_apology'],
    angles_used: [],
  },
  {
    _id: 'seed-0419-5',
    date: '04-19',
    year: 1975,
    category: 'rock',
    event_type: 'chart',
    headline: '"Philadelphia Freedom" hits #1 US',
    artist: 'Elton John',
    summary: 'Written for tennis player Billie Jean King — a tribute song that also happened to be a chart-topping disco-tinged single.',
    sources: ['https://en.wikipedia.org/wiki/Philadelphia_Freedom'],
    interestingness_score: 5.8,
    hook_types: ['secret', 'collab'],
    angles_available: ['the_release', 'billie_jean_king', 'the_writing'],
    angles_used: [],
  },

  // ─────────────────────────────────────────────── 04-20 ──
  {
    _id: 'seed-0420-1',
    date: '04-20',
    year: 1992,
    category: 'rock',
    event_type: 'performance',
    headline: 'Freddie Mercury Tribute Concert at Wembley',
    artist: 'Queen + guests',
    summary: 'Tribute concert for Freddie Mercury featuring David Bowie, Elton John, George Michael, Annie Lennox, Metallica, Guns N\' Roses and others. Raised over £20m for AIDS research.',
    sources: ['https://en.wikipedia.org/wiki/The_Freddie_Mercury_Tribute_Concert'],
    interestingness_score: 9.5,
    hook_types: ['legacy', 'collab'],
    angles_available: ['the_concert', 'bowie_moment', 'elton_moment', 'legacy'],
    angles_used: [],
  },
  {
    _id: 'seed-0420-2',
    date: '04-20',
    year: 1908,
    category: 'jazz',
    event_type: 'birth',
    headline: 'Lionel Hampton born',
    artist: 'Lionel Hampton',
    summary: 'Jazz vibraphone pioneer, bandleader, and key swing-era figure. Collaborated with Benny Goodman and led his own orchestra for decades.',
    sources: ['https://en.wikipedia.org/wiki/Lionel_Hampton'],
    interestingness_score: 6.4,
    hook_types: ['legacy'],
    angles_available: ['the_birth', 'vibraphone_history', 'goodman_collab'],
    angles_used: [],
  },
  {
    _id: 'seed-0420-3',
    date: '04-20',
    year: 1951,
    category: 'rnb',
    event_type: 'birth',
    headline: 'Luther Vandross born',
    artist: 'Luther Vandross',
    summary: 'Eight-time Grammy-winning R&B vocalist. Backing singer for David Bowie ("Young Americans") before his solo breakthrough with "Never Too Much".',
    sources: ['https://en.wikipedia.org/wiki/Luther_Vandross'],
    interestingness_score: 7.2,
    hook_types: ['unknown_fact', 'legacy'],
    angles_available: ['the_birth', 'bowie_backing', 'never_too_much', 'legacy'],
    angles_used: [],
  },
  {
    _id: 'seed-0420-4',
    date: '04-20',
    year: 1972,
    category: 'rock',
    event_type: 'controversy',
    headline: 'John Lennon deportation order issued',
    artist: 'John Lennon',
    summary: 'US immigration orders Lennon to leave the country, citing a 1968 UK cannabis conviction. Legal battle drags on for years before he wins the right to stay in 1976.',
    sources: ['https://en.wikipedia.org/wiki/John_Lennon#Immigration_battle'],
    interestingness_score: 7.8,
    hook_types: ['controversy', 'lawsuit'],
    angles_available: ['the_event', 'the_cannabis_bust', 'nixon_connection', 'the_victory'],
    angles_used: [],
  },
  {
    _id: 'seed-0420-5',
    date: '04-20',
    year: 1999,
    category: 'rock',
    event_type: 'other',
    headline: 'Columbine aftermath — Marilyn Manson scapegoated',
    artist: 'Marilyn Manson',
    summary: 'Columbine High School shooting. In the aftermath, Marilyn Manson was widely (and incorrectly) blamed; he cancelled the remaining US tour and later discussed the media reaction in "Bowling for Columbine".',
    sources: ['https://en.wikipedia.org/wiki/Marilyn_Manson'],
    interestingness_score: 6.8,
    hook_types: ['controversy'],
    angles_available: ['the_aftermath', 'media_scapegoat', 'bowling_for_columbine'],
    angles_used: [],
  },

  // ─────────────────────────────────────────────── 04-21 ──
  {
    _id: 'seed-0421-1',
    date: '04-21',
    year: 2016,
    category: 'pop',
    event_type: 'death',
    headline: 'Prince found dead at Paisley Park',
    artist: 'Prince',
    summary: 'Found unresponsive in an elevator at Paisley Park. Cause: accidental fentanyl overdose. He was 57. Shook the music world and triggered a massive reassessment of his catalogue and legacy.',
    sources: ['https://en.wikipedia.org/wiki/Death_of_Prince'],
    interestingness_score: 10.0,
    hook_types: ['tragedy', 'legacy'],
    angles_available: ['the_day', 'the_vault', 'paisley_park', 'legacy', 'the_last_show'],
    angles_used: [],
  },
  {
    _id: 'seed-0421-2',
    date: '04-21',
    year: 1985,
    category: 'pop',
    event_type: 'chart',
    headline: '"We Are the World" tops US chart',
    artist: 'USA for Africa',
    summary: 'The Michael Jackson / Lionel Richie-written charity single hits #1 in the US. Featured 45+ artists. Raised an estimated $63m for African famine relief.',
    sources: ['https://en.wikipedia.org/wiki/We_Are_the_World'],
    interestingness_score: 8.5,
    hook_types: ['collab', 'legacy'],
    angles_available: ['the_release', 'the_session', 'leave_your_ego', 'the_impact'],
    angles_used: [],
  },
  {
    _id: 'seed-0421-3',
    date: '04-21',
    year: 1978,
    category: 'rock',
    event_type: 'release',
    headline: 'Van Halen release self-titled debut',
    artist: 'Van Halen',
    album: 'Van Halen',
    summary: '"Eruption" redefined what was possible on a guitar; "You Really Got Me" cover announced them as a commercial force.',
    sources: ['https://en.wikipedia.org/wiki/Van_Halen_(album)'],
    interestingness_score: 8.2,
    hook_types: ['debut', 'legacy'],
    angles_available: ['the_release', 'eruption', 'tap_technique', 'debut_impact'],
    angles_used: [],
  },
  {
    _id: 'seed-0421-4',
    date: '04-21',
    year: 2003,
    category: 'rnb',
    event_type: 'death',
    headline: 'Nina Simone dies',
    artist: 'Nina Simone',
    summary: 'High priestess of soul, pianist and civil rights figure. Died at her home in southern France after a long illness, aged 70.',
    sources: ['https://en.wikipedia.org/wiki/Nina_Simone'],
    interestingness_score: 7.8,
    hook_types: ['legacy'],
    angles_available: ['the_event', 'civil_rights_music', 'mississippi_goddam', 'legacy'],
    angles_used: [],
  },
  {
    _id: 'seed-0421-5',
    date: '04-21',
    year: 1969,
    category: 'rock',
    event_type: 'other',
    headline: 'Lennon and Ono "Bed-in" for peace',
    artist: 'John Lennon, Yoko Ono',
    summary: 'Around this time, Lennon and Ono held their second "Bed-in for Peace" in Montreal, later recording "Give Peace a Chance" from the bed.',
    sources: ['https://en.wikipedia.org/wiki/Bed-in'],
    interestingness_score: 6.0,
    hook_types: ['unknown_fact'],
    angles_available: ['the_event', 'give_peace_a_chance', 'media_reaction'],
    angles_used: [],
  },

  // ─────────────────────────────────────────────── 04-22 ──
  {
    _id: 'seed-0422-1',
    date: '04-22',
    year: 1950,
    category: 'rock',
    event_type: 'birth',
    headline: 'Peter Frampton born',
    artist: 'Peter Frampton',
    summary: 'English guitarist and singer. "Frampton Comes Alive!" (1976) became one of the best-selling live albums ever. Pioneer of the talk-box effect.',
    sources: ['https://en.wikipedia.org/wiki/Peter_Frampton'],
    interestingness_score: 6.5,
    hook_types: ['legacy'],
    angles_available: ['the_birth', 'comes_alive', 'talk_box'],
    angles_used: [],
  },
  {
    _id: 'seed-0422-2',
    date: '04-22',
    year: 1983,
    category: 'pop',
    event_type: 'chart',
    headline: '"Beat It" hits #1 US',
    artist: 'Michael Jackson',
    album: 'Thriller',
    summary: 'Eddie Van Halen\'s uncredited guitar solo (he agreed on the condition of anonymity and a case of beer). Second Thriller single to top the chart.',
    sources: ['https://en.wikipedia.org/wiki/Beat_It'],
    interestingness_score: 8.9,
    hook_types: ['secret', 'collab', 'unknown_fact'],
    angles_available: ['the_release', 'eddie_van_halen_solo', 'the_music_video', 'the_gang_theme'],
    angles_used: [],
  },
  {
    _id: 'seed-0422-3',
    date: '04-22',
    year: 1993,
    category: 'rock',
    event_type: 'release',
    headline: 'Radiohead release "Pablo Honey"',
    artist: 'Radiohead',
    album: 'Pablo Honey',
    summary: 'Debut album containing "Creep" — initially stalled in the UK but became a US sleeper hit that would define (and haunt) the band for years.',
    sources: ['https://en.wikipedia.org/wiki/Pablo_Honey'],
    interestingness_score: 7.5,
    hook_types: ['debut', 'secret'],
    angles_available: ['the_release', 'creep_lawsuit', 'the_rejection', 'pre_ok_computer'],
    angles_used: [],
  },
  {
    _id: 'seed-0422-4',
    date: '04-22',
    year: 2008,
    category: 'hip-hop',
    event_type: 'release',
    headline: 'Lil Wayne releases "Lollipop"',
    artist: 'Lil Wayne',
    album: 'Tha Carter III',
    summary: 'Auto-Tuned lead single from Tha Carter III. Went diamond in 2020. Cemented Auto-Tune\'s post-T-Pain mainstream dominance.',
    sources: ['https://en.wikipedia.org/wiki/Lollipop_(Lil_Wayne_song)'],
    interestingness_score: 7.0,
    hook_types: ['legacy'],
    angles_available: ['the_release', 'auto_tune_era', 'the_mixtape_lead_up'],
    angles_used: [],
  },
  {
    _id: 'seed-0422-5',
    date: '04-22',
    year: 1968,
    category: 'rock',
    event_type: 'other',
    headline: 'Apple Records founded by The Beatles',
    artist: 'The Beatles',
    summary: 'Around this time the Beatles launched their Apple Corps and associated label, intended as an artist-friendly alternative to the majors. Early signings: Mary Hopkin, James Taylor, Badfinger.',
    sources: ['https://en.wikipedia.org/wiki/Apple_Records'],
    interestingness_score: 7.2,
    hook_types: ['unknown_fact'],
    angles_available: ['the_founding', 'early_signings', 'business_chaos'],
    angles_used: [],
  },

  // ─────────────────────────────────────────────── 04-23 ──
  {
    _id: 'seed-0423-1',
    date: '04-23',
    year: 1936,
    category: 'rock',
    event_type: 'birth',
    headline: 'Roy Orbison born',
    artist: 'Roy Orbison',
    summary: 'Voice like no-one else in rock and roll. "Only the Lonely", "Crying", "Oh, Pretty Woman". Later a Traveling Wilbury alongside Dylan, Harrison, Lynne and Petty.',
    sources: ['https://en.wikipedia.org/wiki/Roy_Orbison'],
    interestingness_score: 7.8,
    hook_types: ['legacy'],
    angles_available: ['the_birth', 'the_voice', 'traveling_wilburys', 'legacy'],
    angles_used: [],
  },
  {
    _id: 'seed-0423-2',
    date: '04-23',
    year: 1984,
    category: 'rock',
    event_type: 'release',
    headline: 'Deep Purple release "Perfect Strangers"',
    artist: 'Deep Purple',
    album: 'Perfect Strangers',
    summary: 'Reunion album of the classic Mk II line-up after nearly a decade apart. Commercial comeback — title track remains a live staple.',
    sources: ['https://en.wikipedia.org/wiki/Perfect_Strangers_(Deep_Purple_album)'],
    interestingness_score: 6.5,
    hook_types: ['legacy'],
    angles_available: ['the_release', 'the_reunion', 'the_tour'],
    angles_used: [],
  },
  {
    _id: 'seed-0423-3',
    date: '04-23',
    year: 1987,
    category: 'pop',
    event_type: 'birth',
    headline: 'Joss Stone born',
    artist: 'Joss Stone',
    summary: 'British soul singer signed at 15. Debut "The Soul Sessions" (2003) recorded when she was 16 — all covers, and a genuine commercial hit.',
    sources: ['https://en.wikipedia.org/wiki/Joss_Stone'],
    interestingness_score: 5.5,
    hook_types: ['debut'],
    angles_available: ['the_birth', 'teenage_signing', 'the_soul_sessions'],
    angles_used: [],
  },
  {
    _id: 'seed-0423-4',
    date: '04-23',
    year: 2001,
    category: 'other',
    event_type: 'other',
    headline: 'Napster ordered to remove all copyrighted songs',
    artist: 'Napster',
    summary: 'US court ruling forced Napster to filter out all copyrighted music. Effectively ended the first era of mass file sharing and accelerated the industry\'s digital reckoning.',
    sources: ['https://en.wikipedia.org/wiki/Napster'],
    interestingness_score: 7.4,
    hook_types: ['controversy', 'legacy'],
    angles_available: ['the_ruling', 'metallica_lawsuit', 'the_industry_pivot'],
    angles_used: [],
  },
  {
    _id: 'seed-0423-5',
    date: '04-23',
    year: 2011,
    category: 'other',
    event_type: 'other',
    headline: 'Record Store Day',
    artist: 'Various',
    summary: 'Annual Record Store Day (late April) — began in 2007 to celebrate indie record stores. Drove the vinyl revival from niche to mainstream.',
    sources: ['https://en.wikipedia.org/wiki/Record_Store_Day'],
    interestingness_score: 5.0,
    hook_types: ['legacy'],
    angles_available: ['the_origin', 'vinyl_revival', 'rare_releases'],
    angles_used: [],
  },

  // ─────────────────────────────────────────────── 04-24 ──
  {
    _id: 'seed-0424-1',
    date: '04-24',
    year: 1942,
    category: 'pop',
    event_type: 'birth',
    headline: 'Barbra Streisand born',
    artist: 'Barbra Streisand',
    summary: 'EGOT winner. One of the best-selling female artists in history. Career spans Broadway, film, and decades of chart-topping albums.',
    sources: ['https://en.wikipedia.org/wiki/Barbra_Streisand'],
    interestingness_score: 6.8,
    hook_types: ['legacy'],
    angles_available: ['the_birth', 'egot', 'funny_girl', 'the_voice'],
    angles_used: [],
  },
  {
    _id: 'seed-0424-2',
    date: '04-24',
    year: 1976,
    category: 'rock',
    event_type: 'performance',
    headline: 'Bob Marley and the Wailers at the Roxy',
    artist: 'Bob Marley and the Wailers',
    summary: 'Legendary LA Roxy show during the Rastaman Vibration tour. Bootlegs of the performance circulated widely and helped cement Marley\'s US breakthrough.',
    sources: ['https://en.wikipedia.org/wiki/Bob_Marley'],
    interestingness_score: 7.0,
    hook_types: ['legacy'],
    angles_available: ['the_show', 'rastaman_vibration', 'us_breakthrough'],
    angles_used: [],
  },
  {
    _id: 'seed-0424-3',
    date: '04-24',
    year: 1995,
    category: 'rock',
    event_type: 'release',
    headline: 'Oasis release "Some Might Say"',
    artist: 'Oasis',
    album: '(What\'s the Story) Morning Glory?',
    summary: 'First Oasis #1 single in the UK. Noel\'s last recording with original drummer Tony McCarroll — the rift would widen the same week.',
    sources: ['https://en.wikipedia.org/wiki/Some_Might_Say'],
    interestingness_score: 7.3,
    hook_types: ['legacy', 'unknown_fact'],
    angles_available: ['the_release', 'mccarroll_exit', 'britpop_peak'],
    angles_used: [],
  },
  {
    _id: 'seed-0424-4',
    date: '04-24',
    year: 2017,
    category: 'hip-hop',
    event_type: 'release',
    headline: 'Kendrick Lamar releases "DAMN."',
    artist: 'Kendrick Lamar',
    album: 'DAMN.',
    summary: 'Fourth studio album. Won the Pulitzer Prize for Music in 2018 — the first non-classical or jazz work ever to do so.',
    sources: ['https://en.wikipedia.org/wiki/Damn_(Kendrick_Lamar_album)'],
    interestingness_score: 9.2,
    hook_types: ['legacy'],
    angles_available: ['the_release', 'the_pulitzer', 'humble', 'concept'],
    angles_used: [],
  },
  {
    _id: 'seed-0424-5',
    date: '04-24',
    year: 1970,
    category: 'rock',
    event_type: 'release',
    headline: 'Paul McCartney releases first solo album',
    artist: 'Paul McCartney',
    album: 'McCartney',
    summary: 'Released alongside a press statement that, for many, marked the end of The Beatles. Recorded almost entirely by Paul alone at his home studio.',
    sources: ['https://en.wikipedia.org/wiki/McCartney_(album)'],
    interestingness_score: 8.4,
    hook_types: ['breakup', 'legacy'],
    angles_available: ['the_release', 'beatles_split', 'maybe_im_amazed', 'home_recording'],
    angles_used: [],
  },

  // ─────────────────────────────────────────────── 04-25 ──
  {
    _id: 'seed-0425-1',
    date: '04-25',
    year: 1917,
    category: 'jazz',
    event_type: 'birth',
    headline: 'Ella Fitzgerald born',
    artist: 'Ella Fitzgerald',
    summary: '"The First Lady of Song." 13 Grammys. Defined scat, the American songbook, and jazz vocals for generations.',
    sources: ['https://en.wikipedia.org/wiki/Ella_Fitzgerald'],
    interestingness_score: 8.5,
    hook_types: ['legacy'],
    angles_available: ['the_birth', 'the_songbooks', 'scat_origin', 'legacy'],
    angles_used: [],
  },
  {
    _id: 'seed-0425-2',
    date: '04-25',
    year: 1965,
    category: 'electronic',
    event_type: 'birth',
    headline: 'Björk born',
    artist: 'Björk',
    summary: 'Icelandic singer, producer and genre-bender. Debuted as a child, fronted The Sugarcubes, then a solo career that reshaped art-pop and electronic music.',
    sources: ['https://en.wikipedia.org/wiki/Björk'],
    interestingness_score: 8.3,
    hook_types: ['legacy'],
    angles_available: ['the_birth', 'sugarcubes', 'debut', 'biophilia', 'legacy'],
    angles_used: [],
  },
  {
    _id: 'seed-0425-3',
    date: '04-25',
    year: 1983,
    category: 'rock',
    event_type: 'release',
    headline: 'New Order release "Blue Monday"',
    artist: 'New Order',
    summary: '12-inch single — the best-selling 12-inch of all time. Famously lost money on each copy due to the elaborate die-cut sleeve design.',
    sources: ['https://en.wikipedia.org/wiki/Blue_Monday_(New_Order_song)'],
    interestingness_score: 8.8,
    hook_types: ['secret', 'unknown_fact'],
    angles_available: ['the_release', 'the_sleeve_cost', 'the_drum_machine', 'the_influence'],
    angles_used: [],
  },
  {
    _id: 'seed-0425-4',
    date: '04-25',
    year: 1996,
    category: 'hip-hop',
    event_type: 'release',
    headline: 'Fugees "The Score" peak moment',
    artist: 'Fugees',
    album: 'The Score',
    summary: '"Killing Me Softly" cover peaks around this time. The album sold 22m+ copies worldwide and would be their last as a group.',
    sources: ['https://en.wikipedia.org/wiki/The_Score_(Fugees_album)'],
    interestingness_score: 8.2,
    hook_types: ['legacy', 'breakup'],
    angles_available: ['the_release', 'killing_me_softly', 'final_album', 'lauryn_hill_solo'],
    angles_used: [],
  },
  {
    _id: 'seed-0425-5',
    date: '04-25',
    year: 2005,
    category: 'rnb',
    event_type: 'release',
    headline: 'Mariah Carey releases "The Emancipation of Mimi"',
    artist: 'Mariah Carey',
    album: 'The Emancipation of Mimi',
    summary: 'Comeback album after the critical/commercial struggle of "Glitter". 10m+ copies sold, 3 Grammys, restored her as a mainstream force.',
    sources: ['https://en.wikipedia.org/wiki/The_Emancipation_of_Mimi'],
    interestingness_score: 7.7,
    hook_types: ['legacy'],
    angles_available: ['the_release', 'the_comeback', 'we_belong_together', 'glitter_fallout'],
    angles_used: [],
  },
]
